<?php

/**
 * @file
 * SimpleSAMLphp Custom Attribute Mapping module.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_help().
 */
function simplesamlphp_custom_attributes_help($route_name) {
  switch ($route_name) {
    case 'simplesamlphp_custom_attributes.list':
    case 'help.page.simplesamlphp_custom_attributes':
      $output = t('<p>This module saves SimpleSAMLphp attributes to Drupal user fields.</p>');
      return $output;
  }
}

/**
 * Alter a user account after authentication using attribute mapping.
 *
 * @param Drupal\user\UserInterface $account
 *   The user account that can be altered.
 * @param array $attributes
 *   The SimpleSAMLphp attributes for this user.
 *
 * @return Drupal\user\UserInterface
 *   The altered user account.
 */
function simplesamlphp_custom_attributes_simplesamlphp_auth_user_attributes(UserInterface $account, array $attributes) {
  $mappings = \Drupal::config('simplesamlphp_custom_attributes.mappings')->get('mappings');
  foreach ($mappings as $id => $mapping) {
    if (isset($attributes[$mapping['attribute_name']])) {
      $attribute = $attributes[$mapping['attribute_name']];
      if ($attribute) {
        if ($account->hasField($mapping['field_name'])) {
          $account->set($mapping['field_name'], $attribute);
        }
      }
    }
  }
  return $account;
}
