<?php

/**
 * @file
 * This is the contact us module  for executing email trigger.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_mail().
 */
function custom_app_email_mail($key, &$message, $params) {

  switch ($key) {

    case 'ucla_app_emails':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
      break;

  }

}
